"""Top ~100 empresas del S&P 500 por capitalizacion (ticker, nombre).

Lista estatica (la composicion del indice cambia lento). Los tickers usan el
formato de Yahoo Finance (p.ej. BRK-B, no BRK.B). El orden de visualizacion en
la UI es por PRECIO en vivo; este orden inicial es solo de referencia.
"""

SP500_TOP: list[tuple[str, str]] = [
    ("AAPL", "Apple"),
    ("MSFT", "Microsoft"),
    ("NVDA", "Nvidia"),
    ("AMZN", "Amazon"),
    ("GOOGL", "Alphabet (Class A)"),
    ("GOOG", "Alphabet (Class C)"),
    ("META", "Meta Platforms"),
    ("BRK-B", "Berkshire Hathaway"),
    ("LLY", "Eli Lilly"),
    ("AVGO", "Broadcom"),
    ("TSLA", "Tesla"),
    ("JPM", "JPMorgan Chase"),
    ("WMT", "Walmart"),
    ("V", "Visa"),
    ("UNH", "UnitedHealth Group"),
    ("XOM", "Exxon Mobil"),
    ("MA", "Mastercard"),
    ("PG", "Procter & Gamble"),
    ("JNJ", "Johnson & Johnson"),
    ("HD", "Home Depot"),
    ("COST", "Costco"),
    ("ORCL", "Oracle"),
    ("ABBV", "AbbVie"),
    ("BAC", "Bank of America"),
    ("KO", "Coca-Cola"),
    ("MRK", "Merck"),
    ("CVX", "Chevron"),
    ("NFLX", "Netflix"),
    ("AMD", "Advanced Micro Devices"),
    ("PEP", "PepsiCo"),
    ("CRM", "Salesforce"),
    ("TMO", "Thermo Fisher Scientific"),
    ("ADBE", "Adobe"),
    ("LIN", "Linde"),
    ("WFC", "Wells Fargo"),
    ("MCD", "McDonald's"),
    ("CSCO", "Cisco Systems"),
    ("ACN", "Accenture"),
    ("ABT", "Abbott Laboratories"),
    ("DHR", "Danaher"),
    ("GE", "GE Aerospace"),
    ("QCOM", "Qualcomm"),
    ("TXN", "Texas Instruments"),
    ("INTU", "Intuit"),
    ("VZ", "Verizon"),
    ("AMAT", "Applied Materials"),
    ("DIS", "Walt Disney"),
    ("CAT", "Caterpillar"),
    ("PFE", "Pfizer"),
    ("CMCSA", "Comcast"),
    ("PM", "Philip Morris International"),
    ("NOW", "ServiceNow"),
    ("IBM", "IBM"),
    ("UBER", "Uber Technologies"),
    ("GS", "Goldman Sachs"),
    ("SPGI", "S&P Global"),
    ("ISRG", "Intuitive Surgical"),
    ("NEE", "NextEra Energy"),
    ("RTX", "RTX"),
    ("AXP", "American Express"),
    ("HON", "Honeywell"),
    ("T", "AT&T"),
    ("UNP", "Union Pacific"),
    ("LOW", "Lowe's"),
    ("PGR", "Progressive"),
    ("ELV", "Elevance Health"),
    ("BKNG", "Booking Holdings"),
    ("MS", "Morgan Stanley"),
    ("BLK", "BlackRock"),
    ("SYK", "Stryker"),
    ("LMT", "Lockheed Martin"),
    ("MDT", "Medtronic"),
    ("TJX", "TJX Companies"),
    ("VRTX", "Vertex Pharmaceuticals"),
    ("C", "Citigroup"),
    ("BSX", "Boston Scientific"),
    ("ADP", "Automatic Data Processing"),
    ("REGN", "Regeneron Pharmaceuticals"),
    ("MMC", "Marsh & McLennan"),
    ("CB", "Chubb"),
    ("PLD", "Prologis"),
    ("DE", "Deere & Company"),
    ("ETN", "Eaton"),
    ("GILD", "Gilead Sciences"),
    ("ADI", "Analog Devices"),
    ("AMT", "American Tower"),
    ("BMY", "Bristol Myers Squibb"),
    ("MU", "Micron Technology"),
    ("SBUX", "Starbucks"),
    ("SCHW", "Charles Schwab"),
    ("CI", "Cigna"),
    ("BA", "Boeing"),
    ("KLAC", "KLA Corporation"),
    ("SO", "Southern Company"),
    ("MO", "Altria"),
    ("DUK", "Duke Energy"),
    ("ZTS", "Zoetis"),
    ("ICE", "Intercontinental Exchange"),
    ("APH", "Amphenol"),
    ("EQIX", "Equinix"),
    ("PYPL", "PayPal"),
]
